---
title: "Lists - In Class Exercises"
author: "Precious Merenu"
date: "DATA 2401"
output: html_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}
listexample = list(
  suit = "hearts", 
  face = "king",  
  value = 10
)

```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}
listexample = list(
  suit = c("hearts", "diamonds", "club", "spades"), 
  face = c("king", "queen", "jack"), 
  value = c(2, 3, 4, 5, 6, 7, 8, 9, 10)
)

```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")
Newlist[[1]] +1


```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will give all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")
bedit=("Print out of Elements of element a minus the except the second element:\n")
print(b$a[-2])

bedit = (b$a[8:10])
print(bedit)

#Or 

b$a[b$a >7]

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")
x$z = "Newitem"
print(x)

```
